version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Prague
  open-pull-requests-limit: 10
  reviewers:
  - AuHau
  ignore:
  - dependency-name: peer-id
    versions:
    - 0.14.3
    - 0.14.4
    - 0.14.6
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: libp2p
    versions:
    - 0.30.10
    - 0.30.2
    - 0.30.6
    - 0.30.7
    - 0.30.8
    - 0.30.9
  - dependency-name: libp2p-webrtc-star
    versions:
    - 0.20.7
    - 0.21.0
    - 0.21.1
    - 0.21.2
  - dependency-name: libp2p-noise
    versions:
    - 2.0.4
    - 2.0.5
  - dependency-name: libp2p-tcp
    versions:
    - 0.15.2
    - 0.15.3
  - dependency-name: libp2p-mplex
    versions:
    - 0.10.2
  - dependency-name: libp2p-kad-dht
    versions:
    - 0.20.5
    - 0.20.6
